# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )
Rails.application.config.assets.precompile += %w( vendors/bootstrap/dist/css/bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/font-awesome/css/font-awesome.min.css )
Rails.application.config.assets.precompile += %w( vendors/nprogress/nprogress.css )
Rails.application.config.assets.precompile += %w( vendors/iCheck/skins/flat/green.css )
Rails.application.config.assets.precompile += %w( vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css )
Rails.application.config.assets.precompile += %w( vendors/jqvmap/dist/jqvmap.min.css )
Rails.application.config.assets.precompile += %w( vendors/bootstrap-daterangepicker/daterangepicker.css )
Rails.application.config.assets.precompile += %w( build/css/custom.min.css )
Rails.application.config.assets.precompile += %w( vendors/jquery/dist/jquery.min.js )
Rails.application.config.assets.precompile += %w( vendors/bootstrap/dist/js/bootstrap.min.js )
Rails.application.config.assets.precompile += %w( vendors/fastclick/lib/fastclick.js )
Rails.application.config.assets.precompile += %w( vendors/nprogress/nprogress.js )
Rails.application.config.assets.precompile += %w( vendors/Chart.js/dist/Chart.min.js )
Rails.application.config.assets.precompile += %w(vendors/gauge.js/dist/gauge.min.js )
Rails.application.config.assets.precompile += %w( vendors/bootstrap-progressbar/bootstrap-progressbar.min.js )
Rails.application.config.assets.precompile += %w( vendors/iCheck/icheck.min.js )
Rails.application.config.assets.precompile += %w( vendors/skycons/skycons.js )
Rails.application.config.assets.precompile += %w( vendors/Flot/jquery.flot.js )
Rails.application.config.assets.precompile += %w( vendors/Flot/jquery.flot.pie.js )
Rails.application.config.assets.precompile += %w( vendors/Flot/jquery.flot.time.js )
Rails.application.config.assets.precompile += %w( vendors/Flot/jquery.flot.stack.js )
Rails.application.config.assets.precompile += %w( vendors/Flot/jquery.flot.resize.js )
Rails.application.config.assets.precompile += %w( vendors/flot.orderbars/js/jquery.flot.orderBars.js )
Rails.application.config.assets.precompile += %w( vendors/flot-spline/js/jquery.flot.spline.min.js )
Rails.application.config.assets.precompile += %w( vendors/flot.curvedlines/curvedLines.js )
Rails.application.config.assets.precompile += %w( vendors/DateJS/build/date.js )
Rails.application.config.assets.precompile += %w( vendors/jqvmap/dist/jquery.vmap.js )
Rails.application.config.assets.precompile += %w( vendors/jqvmap/dist/maps/jquery.vmap.world.js )
Rails.application.config.assets.precompile += %w( vendors/jqvmap/examples/js/jquery.vmap.sampledata.js )
Rails.application.config.assets.precompile += %w( vendors/moment/min/moment.min.js )
Rails.application.config.assets.precompile += %w( vendors/bootstrap-daterangepicker/daterangepicker.js )
Rails.application.config.assets.precompile += %w( build/js/custom.min.js )
Rails.application.config.assets.precompile += %w( vendors/css/style.css )
Rails.application.config.assets.precompile += %w( //cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.1.1/gh-fork-ribbon.min.css )
Rails.application.config.assets.precompile += %w( vendors/jquery-2.2.3.min.js )
Rails.application.config.assets.precompile += %w( vendors/jquery.form.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-bs/css/dataTables.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css )
Rails.application.config.assets.precompile += %w( vendors/datatables.net/js/jquery.dataTables.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-bs/js/dataTables.bootstrap.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons/js/dataTables.buttons.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons/js/buttons.flash.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons/js/buttons.html5.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-buttons/js/buttons.print.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js)
Rails.application.config.assets.precompile += %w( vendors/datatables.net-keytable/js/dataTables.keyTable.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-responsive/js/dataTables.responsive.min.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js )
Rails.application.config.assets.precompile += %w( vendors/datatables.net-scroller/js/dataTables.scroller.min.js )
Rails.application.config.assets.precompile += %w( vendors/jszip/dist/jszip.min.js )
Rails.application.config.assets.precompile += %w( vendors/pdfmake/build/pdfmake.min.js )
Rails.application.config.assets.precompile += %w( vendors/pdfmake/build/vfs_fonts.js )
Rails.application.config.assets.precompile += %w( loginValidator.js )
Rails.application.config.assets.precompile += %w( login.js )
Rails.application.config.assets.precompile += %w( loginController.js )
Rails.application.config.assets.precompile += %w( newuserController.js )
Rails.application.config.assets.precompile += %w( userValidator.js )
Rails.application.config.assets.precompile += %w( addnewuser.js )
Rails.application.config.assets.precompile += %w( edituserController.js )
Rails.application.config.assets.precompile += %w( edituserValidator.js )
Rails.application.config.assets.precompile += %w( edituser.js )
Rails.application.config.assets.precompile += %w( signupuser.js )
Rails.application.config.assets.precompile += %w( signupValidator.js )
Rails.application.config.assets.precompile += %w( signupController.js )
Rails.application.config.assets.precompile += %w( editpageController.js )
Rails.application.config.assets.precompile += %w( editpageValidator.js )
Rails.application.config.assets.precompile += %w( editpage.js )
Rails.application.config.assets.precompile += %w( newpageController.js )
Rails.application.config.assets.precompile += %w( pageValidator.js )
Rails.application.config.assets.precompile += %w( addnewpage.js )
Rails.application.config.assets.precompile += %w( edittestimonialController.js )
Rails.application.config.assets.precompile += %w( edittestimonialValidator.js )
Rails.application.config.assets.precompile += %w( edittestimonial.js )
Rails.application.config.assets.precompile += %w( newtestimonialController.js )
Rails.application.config.assets.precompile += %w( testimonialValidator.js )
Rails.application.config.assets.precompile += %w( addnewtestimonial.js )
Rails.application.config.assets.precompile += %w( editcontentController.js )
Rails.application.config.assets.precompile += %w( editcontentValidator.js )
Rails.application.config.assets.precompile += %w( editcontent.js )
Rails.application.config.assets.precompile += %w( newcontentController.js )
Rails.application.config.assets.precompile += %w( contentValidator.js )
Rails.application.config.assets.precompile += %w( addnewcontent.js )
Rails.application.config.assets.precompile += %w( editaboutController.js )
Rails.application.config.assets.precompile += %w( editaboutValidator.js )
Rails.application.config.assets.precompile += %w( editabout.js )
Rails.application.config.assets.precompile += %w( newaboutController.js )
Rails.application.config.assets.precompile += %w( aboutValidator.js )
Rails.application.config.assets.precompile += %w( addnewabout.js )
Rails.application.config.assets.precompile += %w( newconfigController.js )
Rails.application.config.assets.precompile += %w( configValidator.js )
Rails.application.config.assets.precompile += %w( addnewconfig.js )
Rails.application.config.assets.precompile += %w( editconfigController.js )
Rails.application.config.assets.precompile += %w( editconfigValidator.js )
Rails.application.config.assets.precompile += %w( editconfig.js )


Rails.application.config.assets.precompile += %w( newsliderController.js )
Rails.application.config.assets.precompile += %w( sliderValidator.js )
Rails.application.config.assets.precompile += %w( addnewslider.js )
Rails.application.config.assets.precompile += %w( editsliderController.js )
Rails.application.config.assets.precompile += %w( editsliderValidator.js )
Rails.application.config.assets.precompile += %w( editslider.js )

Rails.application.config.assets.precompile += %w( newteamController.js )
Rails.application.config.assets.precompile += %w( teamValidator.js )
Rails.application.config.assets.precompile += %w( addnewteam.js )
Rails.application.config.assets.precompile += %w( editteamController.js )
Rails.application.config.assets.precompile += %w( editteamValidator.js )
Rails.application.config.assets.precompile += %w( editteam.js )
Rails.application.config.assets.precompile += %w( slideedit.js  )

Rails.application.config.assets.precompile += %w( vendors/bootstrap.css )

Rails.application.config.assets.precompile += %w( vendors/owl.carousel.css )

Rails.application.config.assets.precompile += %w( vendors/owl.theme.css )

Rails.application.config.assets.precompile += %w( http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css )

Rails.application.config.assets.precompile += %w( vendors/styles.css )

Rails.application.config.assets.precompile += %w( vendors/responsive.css )

Rails.application.config.assets.precompile += %w( vendors/jquery-1.11.2.min.js )

Rails.application.config.assets.precompile += %w( vendors/owl.carousel.js )

Rails.application.config.assets.precompile += %w(vendors/bootstrap.js )